name: struviot
description: "StruvIoT Application"
publish_to: 'none'
version: 0.0.2
environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  qr_code_scanner: ^1.0.1
  shared_preferences: ^2.2.3
  sqflite: ^2.3.3+1
  path_provider: ^2.1.3
  cupertino_icons: ^1.0.6
  mqtt_client: ^9.6.0
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/certs/AmazonRootCA1.pem
    - assets/certs/e914c111ce3626a6a54cd60d77e9752309d09f766491e890d96a4e3abaf5f2ba-certificate.pem.crt
    - assets/certs/e914c111ce3626a6a54cd60d77e9752309d09f766491e890d96a4e3abaf5f2ba-private.pem.key

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Regular.ttf